-- ============================================================
-- Migration: rebuild sterilizer_qa_tests for the per-machine-card
-- QA Testing Log (backlog items #2 QA-BI portion, #3, #4).
--
-- This changes the test_type values (old: 'Weekly Complete Test',
-- 'Bowie-Dick Test', 'BI Preliminary Result', 'BI Final Result',
-- 'Dummy Test Kit' -> new: 'Bowie-Dick', 'BI', 'Dummy'), adds a
-- status column, and adds dummy_ci_result + bi_expected_incubation_hours.
--
-- >>> STOP AND READ BEFORE RUNNING <<<
-- If you have NOT yet logged any real QA tests in production, run
-- Option A below — it's a clean drop-and-recreate of just this one
-- table (nothing else in your database is touched).
--
-- If you HAVE real QA test rows already logged that you need to
-- keep, do NOT run Option A — the old test_type values and the old
-- "BI Preliminary" + "BI Final" as two separate, loosely-linked rows
-- don't map onto the new one-row-per-BI-lifecycle model automatically
-- or safely. Tell Claude you have real data here and a proper
-- row-by-row migration script (pairing preliminary/final rows by
-- serial/lot, splitting old "Weekly Complete Test" rows into three)
-- will be written instead — that's real per-row logic, not something
-- to run blind.
-- ============================================================

-- ---------- OPTION A: no real data yet ----------
drop table if exists sterilizer_qa_tests cascade;
-- Now run the sterilizer_qa_tests CREATE TABLE block from sql/schema.sql
-- (the whole file is safe to re-run — every other table uses
-- `create table if not exists` and won't be touched).
